### ISSUE TITLE
options.uri is a required argument

### ISSUE THREAD

**Issue by lamwingka256** [cyraxx/pogobuf#101]
A very obscured error came up. 

    Unhandled rejection Error: operation timed out after 4513 ms, 5 tries with error: Error: options.uri is a required argument

    at C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird-retry\lib\bluebird-retry.js:102:35

    at tryCatcher (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\util.js:16:23)

    at C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\catch_filter.js:24:41

... ... ...

    at Immediate.Async.drainQueues (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\async.js:17:14)

    at runCallback (timers.js:574:20)

    at tryOnImmediate (timers.js:554:5)

    at processImmediate [as _immediateCallback] (timers.js:533:5)`

This provides no useful information for me to debug at all. All I know is bluebird caught this error.

If I change url to uri in tryCallRPC request, this came up instead: 

    Unhandled rejection Error: .POGOProtos.Networking.Envelopes.RequestEnvelope#unknown12 is not a field: undefined

    at Error (native)

    at MessagePrototype.set (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\protobufjs\dist\protobuf.js:2472:35)

    at MessagePrototype.set (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\protobufjs\dist\protobuf.js:2466:38)

    at Message (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\protobufjs\dist\protobuf.js:2395:34)

    at EventEmitter.Client.buildEnvelope (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\pogobuf\pogobuf\pogobuf.client.js:859:16)

    at e (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\pogobuf\pogobuf\pogobuf.client.js:874:37)

    at Promise._execute (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\debuggability.js:299:9)

    at Promise._resolveFromExecutor (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\promise.js:481:18)

    at new Promise (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\promise.js:77:14)

    at EventEmitter.Client.buildSignedEnvelope (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\pogobuf\pogobuf\pogobuf.client.js:871:16)

    at EventEmitter.Client.tryCallRPC (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\pogobuf\pogobuf\pogobuf.client.js:947:21)

    at retry (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\pogobuf\pogobuf\pogobuf.client.js:931:33)

    at C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird-retry\lib\bluebird-retry.js:66:24

    at tryCatcher (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\util.js:16:23)

    at Function.Promise.attempt.Promise.try (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird\js\release\method.js:39:29)

    at try_once (C:\Users\user\Desktop\scannerV3-spawnPoints\node_modules\bluebird-retry\lib\bluebird-retry.js:65:24)

Any ideas?

**Comment by cyraxx** [comment]
The second error can be fixed by updating pogobuf - it appears that your version of node-pogo-protos is newer than your version of pogobuf.

The first part is a little weirder but try updating first to see if it will fix that as well.

**Comment by lamwingka256** [comment]
Right. I have updated node-pogo-protos.

But then the first error is still there. options.uri is a required argument.

**Comment by joelfi** [comment]
Do you call `client.init()` like [here](https://github.com/cyraxx/pogobuf/blob/master/examples/inventory.js#L28)? The `Error: options.uri is a required argument` is thrown by `request` and indicates that the URL (or URI) parameter has not been set (in [here](https://github.com/cyraxx/pogobuf/blob/749a3ee43f61167304baa8098216edb0f55d0f87/pogobuf/pogobuf.client.js#L988)). If you do not call `init()` with your client, the endpoint is not set and hence the `request` module thinks that the URL/URI is empty.

So, do `client.init()` (like [here](https://github.com/cyraxx/pogobuf/blob/master/examples/inventory.js#L28))

**Comment by lamwingka256** [comment]
Just checked. I thought I did but apparently I did not.

Lesson learned.
