### ISSUE TITLE
Client.init() Operation Timeout

### ISSUE THREAD

**Issue by Mathdrquinn** [cyraxx/pogobuf#135]
```
ptcSignIn(username, password)
    .then(token => {
        console.log(`\n!!!!!!!!!!  SIGN IN SUCCESS !!!!!!!!!!`);
        console.log(`Your token is: ${token}`);
        client = new pogobuf.Client({
            version: 5100, // Use API version 0.51 (minimum version for hashing server)
            useHashingServer: true,
            hashingKey: hashingKey
        });
        client.setAuthInfo('ptc', token);
        setClientPosition(nextGearEntrance);
        return client.init();
    })
```

Throws

```
Error { Error: operation timed out after 6325 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100
    at /Users/brendan.quinn/Projects/PoGo/node_modules/bluebird-retry/lib/bluebird-retry.js:109:35
    at tryCatcher (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/brendan.quinn/Projects/PoGo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  failure: 
   Error: Fetching RPC endpoint failed, received status code 100
       at Request.self.request [as _callback] (/Users/brendan.quinn/Projects/PoGo/node_modules/pogobuf/pogobuf/pogobuf.client.js:1084:36)
       at Request.self.callback (/Users/brendan.quinn/Projects/PoGo/node_modules/pogobuf/node_modules/request/request.js:186:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:192:7)
       at Request.<anonymous> (/Users/brendan.quinn/Projects/PoGo/node_modules/pogobuf/node_modules/request/request.js:1081:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:189:7)
       at IncomingMessage.<anonymous> (/Users/brendan.quinn/Projects/PoGo/node_modules/pogobuf/node_modules/request/request.js:1001:12)
       at Object.onceWrapper (events.js:291:19)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:186:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9),
  code: 'ETIMEDOUT' }
```

**Comment by nicoschmitt** [comment]
Thanks, this is beeing worked out at the moment.
You can switch to my fork if you want to test it: `pogosandbox/pogobuf` in package.json.

**Comment by Mathdrquinn** [comment]
@nicoschmitt thanks for your response.  Im getting this when fetching settings and mapObjects, but I suppose you're already aware of that.  I will look at the fork, thanks and I will look for updates!

**Comment by nicoschmitt** [comment]
thanks. 
it's done, all we need is some testing now so if you can test and give us feedback here it will be awesome.

**Comment by Mathdrquinn** [comment]
I'm working against the latest cyraxx/pogobuf master and still having the same issue with getting either settings or mapObjects.

**Comment by nicoschmitt** [comment]
That is expected.
Like I said you have to use pogosandbox/pogobuf if you want to test the patch.

**Comment by nicoschmitt** [comment]
Fix has been pushed. You may need to delete node_modules before reinstalling npm to be sure you're using up to date modules.

**Comment by DeweyHur** [comment]
I just want you ask something. I set dependency to this project and I initialized like below, like introduced in usage.
          self.instance = new pogobuf.Client();
          self.instance.setAuthInfo('ptc', token);
          return self.instance.init();
But it occurs same error.
"Status code 100 received from RPC"
AFAIK, if I want to use this module more, should I use upper than 5704 and take a token somewhere else?

**Comment by nicoschmitt** [comment]
unfortunatly, api call now require a valid hash which for the time beeing is only available through a paid subscription: https://hashing.pogodev.org/.

**Comment by edswartz** [comment]
My hashing key expired. I just tried to put in a new one, but am getting error code 100.
When it worked I had this in my defaultOptions of pgobuf.client.js:
```
  version: 5702, 
  signatureInfo: {},
  useHashingServer: true, 
  hashingServer: 'https://pokehash.buddyauth.com/',
  hashingKey:'xxxx...' //my old key
```

Now, I've replaced the old key with the new one and am getting error 100.

Reading the Pogodev documentation at ([https://talk.pogodev.org/d/54-getting-started-with-our-api-hashing-service](https://talk.pogodev.org/d/54-getting-started-with-our-api-hashing-service)) it says to change the hashing server to include the api version (see list at https://pokehash.buddyauth.com/api/hash/versions). However when I do this I get this error:
`Unexpected end of JSON input which I'm sure is related to the parsing occurring near the end of pogobuf.client.js`

If I go back to the plain hashing server url (without the api version), but change the version number to 5901, 5902 or 6100 I get an error like this:

> Unsupported version for hashserver: 5902/1.29.2

So am I doing something wrong with pogobuf or is this a problem at buddyauth?

**Comment by nicoschmitt** [comment]
6100 has been forced now, that's the one to be used.
Unfortunatly, I don't think @cyraxx updated pogobuf on npm so you have to use github version (or my fork: pogosandbox/pogobuf).

**Comment by DeweyHur** [comment]
Still doesn't work. I use your forked version, I bought a hashing key and set the version to 6100 but it stopped with RPC 100 error.
I tried those hashing servers.
1. http://hashing.pogodev.io/
3. http://pokehash.buddyauth.com/
4. https://pokehash.buddyauth.com/

Here's my codes.
          self.instance.setOption('version', 6100);
          self.instance.setOption('hashingServer', 'http://hashing.pogodev.io/');
          self.instance.setOption('useHashingServer', true);
Is anything wrong?

**Comment by nicoschmitt** [comment]
could share more code? are you on discord so we can live chat?

**Comment by nicoschmitt** [comment]
Also, setOption is deprecated now, just create the object with options directly, like:

      ```
  client = new pogobuf.Client({
            deviceId: config.device.id,
            authType: config.credentials.type,
            username: config.credentials.user,
            password: config.credentials.password,
            version: config.api.version,
            useHashingServer: config.hashserver.active,
            hashingKey: config.hashserver.key,
            includeRequestTypeInResponse: true,
            proxy: proxyhelper.proxy,
        });
```

**Comment by DeweyHur** [comment]
Here's my github project.
https://github.com/DeweyHur/pokemon-go-helper

And where should I go in discord?

**Comment by nicoschmitt** [comment]
http://http://discord.pogodev.org. There is a channel #api-nodejs, ping niico.

**Comment by cyraxx** [comment]
Closing all issues as this repository is no longer being maintained. See README for further information.
