### ISSUE TITLE
Using Google login gives 403 error

### ISSUE THREAD

**Issue by artheus** [cyraxx/pogobuf#140]
I am using the Inventory example and I get the 403 error.
The Google account does not have 2-factor auth, and I am writing the correct username/email and password. I have also created a pokemon go account with the google mail. Is this a known error in the 1.10.0 version?

I added a console log of the err in the google-login file, here is the complete output:
```
{ Error: 403 error from server
    at IncomingMessage.<anonymous> (/home/artheus/workspace/pogo/node_modules/gpsoauthnode/oauth.js:61:23)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  statusCode: 403,
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: [Object],
        encoding: 'utf8' },
     readable: false,
     domain: null,
     _events: { end: [Object], data: [Function], error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'android.clients.google.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 468,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        write: [Function: writeAfterFIN],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'android.clients.google.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 468,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        write: [Function: writeAfterFIN],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'content-type': 'text/plain; charset=utf-8',
        'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
        pragma: 'no-cache',
        expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
        date: 'Sat, 03 Jun 2017 17:02:21 GMT',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
        server: 'GSE',
        'alt-svc': 'quic=":443"; ma=2592000; v="38,37,36,35"',
        'accept-ranges': 'none',
        vary: 'Accept-Encoding',
        connection: 'close' },
     rawHeaders: 
      [ 'Content-Type',
        'text/plain; charset=utf-8',
        'Cache-Control',
        'no-cache, no-store, max-age=0, must-revalidate',
        'Pragma',
        'no-cache',
        'Expires',
        'Mon, 01 Jan 1990 00:00:00 GMT',
        'Date',
        'Sat, 03 Jun 2017 17:02:21 GMT',
        'X-Content-Type-Options',
        'nosniff',
        'X-Frame-Options',
        'SAMEORIGIN',
        'X-XSS-Protection',
        '1; mode=block',
        'Server',
        'GSE',
        'Alt-Svc',
        'quic=":443"; ma=2592000; v="38,37,36,35"',
        'Accept-Ranges',
        'none',
        'Vary',
        'Accept-Encoding',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 403,
     statusMessage: 'Forbidden',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'android.clients.google.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 468,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        write: [Function: writeAfterFIN],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: true,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {},
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /auth HTTP/1.1\r\nUser-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; Andromax I56D2G Build/LMY47V\r\nContent-type: application/x-www-form-urlencoded\r\nHost: android.clients.google.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/auth',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null },
     read: [Function] } }
Error: Received code 403 from Google login. This could be because your account has 2-Step-Verification enabled. If that is the case, you need to generate an App Password and use that instead of your regular password: https://security.google.com/settings/security/apppasswords
    at google.login (/home/artheus/workspace/pogo/node_modules/pogobuf/pogobuf/pogobuf.googlelogin.js:66:32)
    at /home/artheus/workspace/pogo/node_modules/gpsoauthnode/oauth.js:140:9
    at IncomingMessage.<anonymous> (/home/artheus/workspace/pogo/node_modules/gpsoauthnode/oauth.js:75:49)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by artheus** [comment]
Here is the code I am using (copy+paste from Inventory example)
Only change I made is the gmail and password.
```javascript
'use strict';

/*
    This example script shows how to work with the getInventory() API call and the
    splitInventory() function.
*/
const pogobuf = require('pogobuf'),
    POGOProtos = require('node-pogo-protos');

// Note: To avoid getting softbanned, change these coordinates to something close to where you
// last used your account
const lat = 29.414570,
    lng = 14.943948;

let client;

// Login to Google and get a login token
new pogobuf.GoogleLogin().login('my.address@gmail.com', '**********')
    .then(token => {
        // Initialize the client
        client = new pogobuf.Client({
            authType: 'google',
            authToken: token
        });
        client.setPosition(lat, lng);

        // Uncomment the following if you want to see request/response information on the console
        // client.on('request', console.dir);
        // client.on('response', console.dir);

        // Perform the initial request
        return client.init();
    })
    .then(() => {
        // Get full inventory
        return client.getInventory(0);
    })
    .then(inventory => {
        if (!inventory.success) throw Error('success=false in inventory response');

        // Split inventory into individual arrays and log them on the console
        inventory = pogobuf.Utils.splitInventory(inventory);
        console.log('Full inventory:', inventory);

        console.log('Items:');
        inventory.items.forEach(item => {
            console.log(item.count + 'x ' +
                pogobuf.Utils.getEnumKeyByValue(POGOProtos.Inventory.Item.ItemId, item.item_id));
        });
    })
    .catch(console.error);

```

**Comment by Socratemus** [comment]
Have you got this working? Or is the API outdated?

**Comment by nicoschmitt** [comment]
This api is indeed outdated, try using pogobuf-vnext for now with is the same api but up to date.
However, I don't think I've modified google login. Could you test it?

**Comment by Socratemus** [comment]
Yea, for me it fails with 403 status(both this and pogobuf-vnext). Any idea if the API will work without the paid hash?
Or if there is any other free API?

**Comment by nicoschmitt** [comment]
There is no way to connect to pogo without a hash key

**Comment by nicoschmitt** [comment]
Also, 403 means IP ban

**Comment by cyraxx** [comment]
Closing all issues as this repository is no longer being maintained. See README for further information.
