### ISSUE TITLE
getCellIDs is not defined

### ISSUE THREAD

**Issue by yaniqt** [cyraxx/pogobuf#21]
In the example, getCellIDs is not defined. Is this is a mismatch in the current release and the documentation? I cannot find any reference to function getCellIDs in any of the included packages.

Thanks

**Comment by cyraxx** [comment]
It's right here: https://github.com/cyraxx/pogobuf/blob/master/examples/gym-details.js#L96

Are you getting an error message when you run the example? Because it seems to run fine for me.

**Comment by yaniqt** [comment]
Sorry, I had assumed this was part of a different package.

Error is as follows;

`Unhandled rejection ReferenceError: getCellIDs is not defined
    at null.<anonymous> (/Users/*****/Projects/Tests/pgo/server.js:35:19)
    at tryCatcher (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/david/Projects/Tests/pgo/node_modules/bluebird/js/release/async.js:16:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`

**Comment by yaniqt** [comment]
Huge user error - my apologies for wasting your time. Please delete :) Love the library. Thanks.
