### ISSUE TITLE
Missing error event (unknown location)

### ISSUE THREAD

**Issue by renedx** [cyraxx/pogobuf#41]
Running the app for a while and connection is lost to server, it crashes:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

It prob is a lib used outside this lib. But checked Google Auth and it does seem to handle the error. So it would be the request lib.. huh..

Anyone running into this/more info would be highly appreciated.

**Comment by renedx** [comment]
Not ran into this for a while. Closing it for now.
