### ISSUE TITLE
Error logging in from AWS EC2 instance

### ISSUE THREAD

**Issue by Eric-Carlton** [cyraxx/pogobuf#50]
I'm getting a list of pokemon from the API. The following works on localhost: 

`login.login(req.body.username, req.body.password).then(token => {
			client.setAuthInfo(req.body.type.toLowerCase(), token);
			client.setPosition(lat, lng);
			client.init().then(() => {
				client.getInventory(0).then(inventory => {
					if (!inventory.success){
						sendResponse(res, 500, {error: props.errors.inventory}, req.body.username, endpoint);
					}
					sendResponse(res, 200, {pokemon: pogobuf.Utils.splitInventory(inventory).pokemon}, req.body.username, endpoint);
				}, err => {
					log.error({err: err.message});
					sendResponse(res, 500, {error: props.errors.inventory}, req.body.username, endpoint)
				});
			});
		}, err => {
			log.error({err: err.message});
			sendResponse(res, 500, {error: props.errors.login}, req.body.username, endpoint);
		});`

However, when deployed to an EC2 instance, I get: 

`Unhandled rejection Error: operation timed out after 4574 ms, 5 tries with error: Status code 403 received from HTTPS request
    at /home/ubuntu/PokemonGoReader/node_modules/bluebird-retry/lib/bluebird-retry.js:102:35
    at tryCatcher (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/util.js:16:23)
    at /home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/promise.js:681:18)
    at Async._drainQueue (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/PokemonGoReader/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
`

Anyone have any idea what's happening?

**Comment by MakuraYami** [comment]
[yes] (https://m.reddit.com/r/pokemongodev/comments/4vhygk/vps_providers_banned_from_accessing_apis)

**Comment by cyraxx** [comment]
Yup, the login is actually not the issue, it's the `init()` call which fails because Niantic blocked AWS IPs (and others) from accessing the API.

**Comment by Eric-Carlton** [comment]
Cool, thanks!

**Comment by glaggia-larus** [comment]
is there a solution to bypass this problem still remaining in a server of that type?

**Comment by joelfi** [comment]
@glaggia-larus you could use proxies.

**Comment by cyraxx** [comment]
There's nothing the library could do to bypass if your host's IP is blocked by Niantic. Your only option is using a proxy or a different host.
