### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by mbeaudru** [cyraxx/pogobuf#65]
Hi guys, it seems that there are many libs missing when I try to use the library as my console is litteraly shouting at me:

```
ERROR in ./~/request/lib/cookies.js
Module not found: Error: Cannot resolve module 'tough-cookie' in E:\Projets\pkmn-go\node_modules\request\lib
resolve module tough-cookie in E:\Projets\pkmn-go\node_modules\request\lib
  looking for modules in E:\Projets\pkmn-go\node_modules
    resolve 'file' tough-cookie in E:\Projets\pkmn-go\node_modules
      resolve file
        E:\Projets\pkmn-go\node_modules\tough-cookie doesn't exist
        E:\Projets\pkmn-go\node_modules\tough-cookie.js doesn't exist
        E:\Projets\pkmn-go\node_modules\tough-cookie.jsx doesn't exist
    E:\Projets\pkmn-go\node_modules\tough-cookie doesn't exist (module as directory)
[E:\Projets\pkmn-go\node_modules\tough-cookie]
[E:\Projets\pkmn-go\node_modules\tough-cookie.js]
[E:\Projets\pkmn-go\node_modules\tough-cookie.jsx]
[E:\Projets\pkmn-go\node_modules\tough-cookie]
 @ ./~/request/lib/cookies.js 3:12-35
ERROR in ./~/mime-db/db.json
Module parse failed: E:\Projets\pkmn-go\node_modules\mime-db\db.json Unexpected token (2:40)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:40)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/mime-db/index.js 11:17-37
ERROR in ./~/request/request.js
Module not found: Error: Cannot resolve module 'forever-agent' in E:\Projets\pkmn-go\node_modules\request
resolve module forever-agent in E:\Projets\pkmn-go\node_modules\request
  looking for modules in E:\Projets\pkmn-go\node_modules
    resolve 'file' forever-agent in E:\Projets\pkmn-go\node_modules
      resolve file
        E:\Projets\pkmn-go\node_modules\forever-agent doesn't exist
        E:\Projets\pkmn-go\node_modules\forever-agent.js doesn't exist
        E:\Projets\pkmn-go\node_modules\forever-agent.jsx doesn't exist
    E:\Projets\pkmn-go\node_modules\forever-agent doesn't exist (module as directory)
[E:\Projets\pkmn-go\node_modules\forever-agent]
[E:\Projets\pkmn-go\node_modules\forever-agent.js]
[E:\Projets\pkmn-go\node_modules\forever-agent.jsx]
[E:\Projets\pkmn-go\node_modules\forever-agent]
 @ ./~/request/request.js 17:19-43
ERROR in ./~/request/lib/har.js
Module not found: Error: Cannot resolve module 'fs' in E:\Projets\pkmn-go\node_modules\request\lib
resolve module fs in E:\Projets\pkmn-go\node_modules\request\lib
  looking for modules in E:\Projets\pkmn-go\node_modules
    resolve 'file' fs in E:\Projets\pkmn-go\node_modules
      resolve file
        E:\Projets\pkmn-go\node_modules\fs doesn't exist
        E:\Projets\pkmn-go\node_modules\fs.js doesn't exist
        E:\Projets\pkmn-go\node_modules\fs.jsx doesn't exist
    E:\Projets\pkmn-go\node_modules\fs doesn't exist (module as directory)
[E:\Projets\pkmn-go\node_modules\fs]
[E:\Projets\pkmn-go\node_modules\fs.js]
[E:\Projets\pkmn-go\node_modules\fs.jsx]
[E:\Projets\pkmn-go\node_modules\fs]
 @ ./~/request/lib/har.js 3:9-22
ERROR in ./~/har-validator/lib/schemas/cache.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\cache.json Unexpected token (2:14)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:14)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 4:9-32
ERROR in ./~/har-validator/lib/schemas/cacheEntry.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\cacheEntry.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 5:14-42
ERROR in ./~/har-validator/lib/schemas/content.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\content.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 6:11-36
ERROR in ./~/har-validator/lib/schemas/cookie.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\cookie.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 7:10-34
ERROR in ./~/har-validator/lib/schemas/creator.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\creator.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 8:11-36
ERROR in ./~/har-validator/lib/schemas/entry.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\entry.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 9:9-32
ERROR in ./~/har-validator/lib/schemas/har.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\har.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 10:7-28
ERROR in ./~/har-validator/lib/schemas/log.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\log.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 11:7-28
ERROR in ./~/har-validator/lib/schemas/page.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\page.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 12:8-30
ERROR in ./~/har-validator/lib/schemas/pageTimings.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\pageTimings.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 13:15-44
ERROR in ./~/har-validator/lib/schemas/postData.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\postData.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 14:12-38
ERROR in ./~/har-validator/lib/schemas/record.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\record.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 15:10-34
ERROR in ./~/har-validator/lib/schemas/request.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\request.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 16:11-36
ERROR in ./~/har-validator/lib/schemas/response.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\response.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 17:12-38
ERROR in ./~/har-validator/lib/schemas/timings.json
Module parse failed: E:\Projets\pkmn-go\node_modules\har-validator\lib\schemas\timings.json Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:12)
    at Parser.pp$4.raise (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Projets\pkmn-go\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/har-validator/lib/schemas/index.js 18:11-36
ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'net' in E:\Projets\pkmn-go\node_modules\tunnel-agent
resolve module net in E:\Projets\pkmn-go\node_modules\tunnel-agent
  looking for modules in E:\Projets\pkmn-go\node_modules
    resolve 'file' net in E:\Projets\pkmn-go\node_modules
      resolve file
        E:\Projets\pkmn-go\node_modules\net doesn't exist
        E:\Projets\pkmn-go\node_modules\net.js doesn't exist
        E:\Projets\pkmn-go\node_modules\net.jsx doesn't exist
    E:\Projets\pkmn-go\node_modules\net doesn't exist (module as directory)
[E:\Projets\pkmn-go\node_modules\net]
[E:\Projets\pkmn-go\node_modules\net.js]
[E:\Projets\pkmn-go\node_modules\net.jsx]
[E:\Projets\pkmn-go\node_modules\net]
 @ ./~/tunnel-agent/index.js 3:10-24
ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in E:\Projets\pkmn-go\node_modules\tunnel-agent
resolve module tls in E:\Projets\pkmn-go\node_modules\tunnel-agent
  looking for modules in E:\Projets\pkmn-go\node_modules
    resolve 'file' tls in E:\Projets\pkmn-go\node_modules
      resolve file
        E:\Projets\pkmn-go\node_modules\tls doesn't exist
        E:\Projets\pkmn-go\node_modules\tls.js doesn't exist
        E:\Projets\pkmn-go\node_modules\tls.jsx doesn't exist
    E:\Projets\pkmn-go\node_modules\tls doesn't exist (module as directory)
[E:\Projets\pkmn-go\node_modules\tls]
[E:\Projets\pkmn-go\node_modules\tls.js]
[E:\Projets\pkmn-go\node_modules\tls.jsx]
[E:\Projets\pkmn-go\node_modules\tls]
 @ ./~/tunnel-agent/index.js 4:10-24
```

Sorry for the huge copy-pasta. Any ideas ?

**Comment by mbeaudru** [comment]
In order to use pogobuf with webpack, just put this in webpack.config.js:

```json
  node: {
    fs: "empty",
    tls: "empty",
    net: "empty"
  }
```

I also had to add **json-loader** to compile properly.

**Comment by travisfisher** [comment]
I added the entry @mbeaudru mentioned but more missing modules popped up afterwards:
````
These dependencies were not found:

* jodid25519 in ./~/sshpk/lib/private-key.js, ./~/sshpk/lib/dhe.js
* jsbn in ./~/sshpk/lib/dhe.js
* ecc-jsbn in ./~/sshpk/lib/dhe.js
* bcrypt-pbkdf in ./~/sshpk/lib/formats/ssh-private.js
* ecc-jsbn/lib/ec in ./~/sshpk/lib/dhe.js
````
I tried adding them to @mbeaudru's node object but they are still popping up. 

Does json-loader resolve these dependencies?

**Comment by mbeaudru** [comment]
Dumb question, but did you try to install sshpk ?
