### ISSUE TITLE
5 tries with error: Fetching RPC endpoint failed, received status code 51

### ISSUE THREAD

**Issue by Eric-Carlton** [cyraxx/pogobuf#85]
Hey all,

As of tonight, I'm getting the error in the title when trying to log in with a Google account. This was working about 4 hours ago with the same code. I'm using PogoBuf 1.5.2. Relevant code below:

```
let getToken = (credential) => {
	return new Promise((resolve, reject) => {
		let login = null;

		if(credential.login_type === 'google'){
			login = new pogobuf.GoogleLogin();
		} else {
			login = new pogobuf.PTCLogin();
		}

		login.login(credential.username, credential.password).then(token => {
			resolve(token);
		}, err => {
			log.trace('login.login() failed, rejecting from getToken');
			reject(err);
		});
	});
}

...

log.trace({credential: credential}, 'calling getToken() from getClient()');
				getToken(credential).then(token => {
					log.trace({token: token, credential: credential}, 'setting auth info on client');
					client.setAuthInfo(credential.login_type, token);
					client.init().then(() => {
						resolve(client);
					}, err => {
						log.trace('client.init() failed, rejecting from getClient');
						reject(err);
					});
				}, err => {
					log.trace('getToken() failed, rejecting from getClient');
					reject(err);
				});
```

And the log output:

```
[2016-08-20T01:14:07.549Z] TRACE: server.pokemonUtils/10386 on MacBook-Pro.local: calling getToken() from getClient()
    credential: {
      "login_type": "google",
      "token": null,
      "username": "xxx",
      "password": "xxx"
    }
[2016-08-20T01:14:08.636Z] TRACE: server.pokemonUtils/10386 on MacBook-Pro.local: setting auth info on client
    token: xxx
    --
    credential: {
      "login_type": "google",
      "token": null,
      "username": "xxx@gmail.com",
      "password": "xxx"
    }
[2016-08-20T01:14:13.745Z] TRACE: server.pokemonUtils/10386 on MacBook-Pro.local: client.init() failed, rejecting from getClient
[2016-08-20T01:14:13.746Z] ERROR: server.pokemonRoutes/10386 on MacBook-Pro.local: pokemonUtils.getClient() failed
    err: operation timed out after 5105 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 51

```

Any ideas what could be going on?

**Comment by richie3366** [comment]
I'm getting the same error, I thought initially that was an IP-ban, but I was getting the same result at home with a random IP and a legit PTC account.

So I guess that pogobuf has not implemented correctly the fetching-RPC request/proto [?] and Niantic has decided to be strict with this request

OR maybe it was an old implentation that may have changed since the recent updates and Niantic has just decided to drop support for this old protocol [?]

Thanks in advance to the guy(s) that will find the solution to this problem! ;)

**Comment by Eric-Carlton** [comment]
Oh yeah, I forgot to mention, I can sign in from the Pokemon Go app just fine over the same network that I'm running those requests from, so it's not an account or IP ban.

**Comment by khag7** [comment]
Also getting RPC error 51 when attempting to log in. Tried another IP with a clean PTC account, no luck.

**Comment by comcaptain** [comment]
**SOLUTION**
go to file pogobuf.client.js, in line 195, change code from
```
message: new RequestMessages.GetPlayerMessage({
    app_version: appVersion
}),
```

to `message: new RequestMessages.GetPlayerMessage({}),`

**Comment by richie3366** [comment]
Thank you @comcaptain, it works well as a temporary (maybe definititive?) fix, good job & thanks for sharing it with us! ;)

**Comment by Shibby7986** [comment]
Same issue for me.
Error as follows...

Failed to initialize client... ERROR: { Error: operation timed out after 6596 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 51
    at C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird-retry\lib\bluebird-retry.js:102:35
    at tryCatcher (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\catch_filter.js:24:41
    at tryCatcher (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\promise.js:681:18)
    at Async._drainQueue (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
  failure:
   Error: Fetching RPC endpoint failed, received status code 51
       at Error (native)
       at Request.self.request.e [as _callback] (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\pogobuf\pogobuf\pogobuf.client.js:1000:36)
       at Request.self.callback (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\request\request.js:187:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:191:7)
       at Request.<anonymous> (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\request\request.js:1044:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at IncomingMessage.<anonymous> (C:\Git\New folder\ptc-acc-gen\PogoPlayer\node_modules\request\request.js:965:12)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:975:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9),
  code: 'ETIMEDOUT' }

**Comment by Eric-Carlton** [comment]
@comcaptain That worked, thanks! As soon as that is implemented in master, I'll close this issue

**Comment by Shibby7986** [comment]
worked for me too :)

**Comment by MomoGunz** [comment]
**Another solution**
pogobuf.client.js:195
Change `.getPlayer('0.31.1')` to `.getPlayer()`

**Comment by khag7** [comment]
I'd argue that MomoGunz solution is better, leave the ability to add the version back into `getPlayer` if that becomes necessary in the future.

**Comment by Eric-Carlton** [comment]
@khag7 that works as well. I'm down for whatever works

**Comment by skmetaly** [comment]
thanks @comcaptain . Seems to fix the issue :)

**Comment by cyraxx** [comment]
Weird that they first introduce the app version field and then require you to not send it. ¯\\\_(ツ)_/¯

Thanks for figuring this out, it's patched in master and I will publish a patch release to npm right away.
